[listener] 
type="socket"

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
ports=["tcp/8022"]
services=["ssh-simulator"]

[channel.console]
type="console"

[[filter]]
channel=["console"]

[channel.tofile]
type="file"
filename="/var/log/honeytrap/action.log"
maxsize="536870912"
timeout="5s"

[[filter]]
channel=["tofile"]

[[logging]]
output="stdout"
level="debug"
