[listener]
type="socket"

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
ports=["tcp/8022"]
services=["ssh-simulator"]

[service.telnet]
type="telnet"
prompt=">"

[[port]]
ports=["tcp/23"]
services=["telnet"]

[channel.console]
type="console"

[[filter]]
channel=["console"]

[channel.tofile]
type="file"
filename="/var/log/honeytrap/action.log"
maxsize="536870912"
timeout="5s"

[[filter]]
channel=["tofile"]

[[logging]]
output="stdout"
level="debug"
