version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
    networks:
      - honeytrap
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.9
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      - elasticsearch
    networks:
      - honeytrap
networks:
  honeytrap:
    external: true
